### PR TITLE
Allow guestlib to find open-vm-tools version

### PR DESCRIPTION
**Pull request by stevenschlansker**

### CODE REVIEW

**Comment by dagwieers** [comment]
Looks good, but why print the date/time ?

**Comment by stevenschlansker** [comment]
It's useful to correlate with other sources of data -- I was trying to e.g. correlate it with JVM pauses or spikes on our Kibana dashboard.  It makes the log much more useful for postmortem.

If you don't like it I can take it out, it just seems like it might help someone else out some day.

**Comment by makefu** [comment]
@stevenschlansker i suggest you remove the timestamp addition from this PR and create a new one. It is always better to have separate PRs for different features added to the project.

**Comment by stevenschlansker** [comment]
done as #3

**Pull request merged**
